### ISSUE TITLE
Why specifically the pico?

### ISSUE THREAD

**Issue by buzzy** [X360Tools/PicoFlasher#32]
I am just curious why this is made specifically for the Pico? Why would this not work on any ARM-based computer, like the Banana Pi? Isn't all you need some GPIO pins and SPI support? If someone knows, please explain.

**Comment by georgewoodall82** [comment]
because a pico is super cheap

**Comment by buzzy** [comment]
> because a pico is super cheap

But nobody has one laying around, while thousands of us have a Raspberry Pi.

**Comment by georgewoodall82** [comment]
its also more convenient because it boots instantly and doesnt need an external power source, it can just be plugged directly into a laptop and nothing else.

**Comment by Soundtoxin** [comment]
> > because a pico is super cheap
> 
> But nobody has one laying around, while thousands of us have a Raspberry Pi.

$4 at your local Micro Center, and you can buy a bunch, they have never been out of stock when I've gone there. Plus drag-and-drop flashing. Lots of projects are using the Pico these days.

**Comment by buzzy** [comment]
> > > because a pico is super cheap
> > 
> > But nobody has one laying around, while thousands of us have a Raspberry Pi.
> 
> $4 at your local Micro Center, and you can buy a bunch, they have never been out of stock when I've gone there. Plus drag-and-drop flashing. Lots of projects are using the Pico these days.

Please let me know where I can find a Micro Center in Europe. Thanks.

**Comment by Soundtoxin** [comment]
Just an example for me personally, not everyone will have one in their state in the US even, though I hear Fry's is similar. I would check whatever local computer/electronics shops you have, otherwise you can order online, though it usually costs a few bucks more on Amazon and similar. Should still be under $15 I would say, and again, stock is healthy. I have heard the Raspberry Pi SBCs have had stock issues for a while now.
